### ISSUE TITLE
Directory Name is Invalid

### ISSUE THREAD

**Issue by Rokkubro** [pleonex/AiroRom#1]
Hi! I've managed to build the "Layton4" project successfully, however the program does not seem to accept input in the form of raw ".fa"(GSFA) files, and throws a system exception of "The directory name is invalid". Do you have any info on the usage of your application? I'm interested to use it to put "London Life" on the UK version of the game. Thanks!

**Comment by pleonex** [comment]
Hi and thanks for the interest!

The project is not finished yet, I will continue working on it soon. At the moment it search for a file named _lt4_main_sp.fa_ (main file in the Spanish edition) and export _only_ the header.

My idea is to be able to export and import all the files easily so you will be able to do it. I will close the issue once it's done so you will know.

**Comment by Rokkubro** [comment]
Ah OK, thanks for the reply! I'll follow this closely, looking forward to your work!

**Comment by pleonex** [comment]
Requests for Professor Layton games to continue in new repository: https://github.com/pleonex/LayTea
