### ISSUE TITLE
Estructura del bloque 4 en The Last Specter

### ISSUE THREAD

**Issue by oldmud0** [pleonex/AiroRom#2]
Hola,

Estoy interesado en la documentacion de la [estructura del cuarto bloque para Professor Layton and the Last Specter](https://github.com/pleonex/AiroRom/wiki/Professor-Layton-and-The-Last-Specter#bloque-4-file--folder-name-table). En contraste con los otros bloques, no hay una tabla detallando los contenidos de este bloque. Lo pregunto porque un amigo mio esta interesado en extrayendo los archivos, a lo mejor a traves de una utilidad como QuickBMS. Si el no lo logra, pues yo lo tratare en C.

Si puedes formar una tabla para ese bloque, lo agradeceria. Muchas gracias.

**Comment by pleonex** [comment]
Requests of Layton games to continue in https://github.com/pleonex/LayTea repository.
